### ISSUE TITLE
✅ Test: 채팅 메세지, 채팅방 Service 단위 테스트코드 추가

### ISSUE THREAD

**Issue by megaseunghan** [challenge-team-kotlin/camp-daddy#59]
## 어떤 테스트 코드를 추가/수정/삭제하시나요?
- [ChatMessage, ChatRoom] Service 단위 테스트 코드를 작성합니다.

## 추가/수정/삭제하는 이유는 무엇인가요?
- 비즈니스 로직이 변경 되었을 때, 정책에서 벗어나지 않는지 쉽게 추적할 수 있게 됩니다.

**Comment by soang94** [comment]
닫아있!
